module.exports=[
    require('vision'),
    require('inert'),
    require('./db'),
    require('./user'),
    require('./chat'),
    require('./publication'),
    require('./messages'),
    require('./tienda'),
    require('./category'),
    require('./filter')
]